import type { ComponentType } from 'react'

import Ace2 from './Ace2'
import Ace2Src from './Ace2.tsx?raw'
import Aquaporin from './Aquaporin'
import AquaporinSrc from './Aquaporin.tsx?raw'
import ColorSchemes from './ColorSchemes'
import ColorSchemesSrc from './ColorSchemes.tsx?raw'
import CytochromeC from './CytochromeC'
import CytochromeCSrc from './CytochromeC.tsx?raw'
import Domains from './Domains'
import DomainsSrc from './Domains.tsx?raw'
import Ef1a from './Ef1a'
import Ef1aSrc from './Ef1a.tsx?raw'
import Globin from './Globin'
import GlobinSrc from './Globin.tsx?raw'
import Hammerhead from './Hammerhead'
import HammerheadSrc from './Hammerhead.tsx?raw'
import HistoneH4 from './HistoneH4'
import HistoneH4Src from './HistoneH4.tsx?raw'
import Hox from './Hox'
import HoxSrc from './Hox.tsx?raw'
import Insulin from './Insulin'
import InsulinSrc from './Insulin.tsx?raw'
import LargeTree from './LargeTree'
import LargeTreeSrc from './LargeTree.tsx?raw'
import LoadFromUrl from './LoadFromUrl'
import LoadFromUrlSrc from './LoadFromUrl.tsx?raw'
import ModelApi from './ModelApi'
import ModelApiSrc from './ModelApi.tsx?raw'
import Myd88 from './Myd88'
import Myd88Src from './Myd88.tsx?raw'
import NucleotideAlignment from './NucleotideAlignment'
import NucleotideAlignmentSrc from './NucleotideAlignment.tsx?raw'
import Opsins from './Opsins'
import OpsinsSrc from './Opsins.tsx?raw'
import P53 from './P53'
import P53Src from './P53.tsx?raw'
import Prestin from './Prestin'
import PrestinSrc from './Prestin.tsx?raw'
import ProgrammaticControl from './ProgrammaticControl'
import ProgrammaticControlSrc from './ProgrammaticControl.tsx?raw'
import RealDomains from './RealDomains'
import RealDomainsSrc from './RealDomains.tsx?raw'
import TreeOptions from './TreeOptions'
import TreeOptionsSrc from './TreeOptions.tsx?raw'
import Trna from './Trna'
import TrnaSrc from './Trna.tsx?raw'
import ZeroConfig from './ZeroConfig'
import ZeroConfigSrc from './ZeroConfig.tsx?raw'

export interface Example {
  name: string
  description: string
  Component: ComponentType
  source: string
}

export const examples: Example[] = [
  {
    name: 'Zero-config viewer',
    description:
      'The simplest usage: pass alignment + tree text as strings to MSAViewer.',
    Component: ZeroConfig,
    source: ZeroConfigSrc,
  },
  {
    name: 'Nucleotide alignment',
    description:
      'A DNA alignment with no tree, using a nucleotide color scheme.',
    Component: NucleotideAlignment,
    source: NucleotideAlignmentSrc,
  },
  {
    name: 'Color schemes',
    description:
      'Switch color schemes at runtime via model.setColorSchemeName.',
    Component: ColorSchemes,
    source: ColorSchemesSrc,
  },
  {
    name: 'Model API',
    description:
      'Create the model yourself with MSAModelF and render it with MSAView.',
    Component: ModelApi,
    source: ModelApiSrc,
  },
  {
    name: 'Programmatic control',
    description: 'Drive the viewer by calling model actions from buttons.',
    Component: ProgrammaticControl,
    source: ProgrammaticControlSrc,
  },
  {
    name: 'Tree options',
    description:
      'Toggle branch lengths, label alignment, node bubbles, and the tree panel.',
    Component: TreeOptions,
    source: TreeOptionsSrc,
  },
  {
    name: 'Protein domains',
    description:
      'Overlay InterProScan domain annotations from an inline GFF3 string.',
    Component: Domains,
    source: DomainsSrc,
  },
  {
    name: 'Real domains (Src-family kinases)',
    description:
      'A real Src-family kinase family (SRC, FYN, LCK, ...) with its tree and ' +
      'real InterProScan annotations — the signature SH3 + SH2 + kinase ' +
      'domains generated by react-msaview-cli interproscan.',
    Component: RealDomains,
    source: RealDomainsSrc,
  },
  {
    name: 'Large tree (Lysine riboswitch)',
    description:
      'A real ~60 sequence ncRNA family (Rfam Lysine riboswitch) with its ' +
      'full inferred tree — shows the canvas tiling holds up past toy data.',
    Component: LargeTree,
    source: LargeTreeSrc,
  },
  {
    name: 'RNA secondary structure (tRNA)',
    description:
      'Transfer RNA (Rfam RF00005): the Stockholm SS_cons cloverleaf renders ' +
      'as a secondary-structure track, coloring the acceptor stem and D/' +
      'anticodon/T arms by base-pairing above the alignment.',
    Component: Trna,
    source: TrnaSrc,
  },
  {
    name: 'Ribozyme structure (hammerhead)',
    description:
      'Hammerhead ribozyme (Rfam RF00008), a small self-cleaving catalytic ' +
      'RNA: the SS_cons track shows its three-way helix junction colored by ' +
      'base-pairing — a catalytic-RNA counterpoint to the tRNA cloverleaf.',
    Component: Hammerhead,
    source: HammerheadSrc,
  },
  {
    name: 'Reference dots (MyD88 across bats)',
    description:
      'MyD88 across mammals incl. bats, diffed against human (relativeTo) so ' +
      'identical residues show as dots and lineage-specific changes stand out, ' +
      'beside the inferred tree.',
    Component: Myd88,
    source: Myd88Src,
  },
  {
    name: 'Gene duplication (globin family)',
    description:
      'Hemoglobin alpha/beta, myoglobin, neuroglobin and cytoglobin — the ' +
      'inferred tree groups by globin type, not species: the signature of ' +
      'gene duplication.',
    Component: Globin,
    source: GlobinSrc,
  },
  {
    name: 'Host range (ACE2 / SARS-CoV-2 receptor)',
    description:
      'ACE2 across mammals (bats, civet, pangolin, resistant rodents) diffed ' +
      'against human, so the few spike-contact positions that drive viral ' +
      'susceptibility stand out.',
    Component: Ace2,
    source: Ace2Src,
  },
  {
    name: 'Color vision (opsin duplications)',
    description:
      'Vertebrate opsins sorted by class (rhodopsins vs cone opsins) with a ' +
      'real InterProScan 7TM-GPCR domain overlay — a color-vision duplication ' +
      'history.',
    Component: Opsins,
    source: OpsinsSrc,
  },
  {
    name: 'Channel family (aquaporins)',
    description:
      'The aquaporin (MIP) family: all share one six-transmembrane domain ' +
      '(InterProScan overlay) but the tree splits water-only channels from the ' +
      '"_glycerol" aquaglyceroporins — grouping by function.',
    Component: Aquaporin,
    source: AquaporinSrc,
  },
  {
    name: 'Extreme conservation (histone H4)',
    description:
      'Histone H4 across eukaryotes diffed against human — one of the most ' +
      'conserved proteins known renders almost entirely as dots, the opposite ' +
      'extreme from a fast-evolving protein.',
    Component: HistoneH4,
    source: HistoneH4Src,
  },
  {
    name: 'Deep phylogeny (cytochrome c)',
    description:
      'Cytochrome c from mammals to plants and fungi in one short alignment — ' +
      'the inferred tree spans over a billion years of evolution.',
    Component: CytochromeC,
    source: CytochromeCSrc,
  },
  {
    name: 'Convergent evolution (prestin / echolocation)',
    description:
      'Prestin (SLC26A5): echolocating bats and toothed whales convergently ' +
      'evolved shared changes, so the "_echo" species cluster together against ' +
      'the species tree.',
    Component: Prestin,
    source: PrestinSrc,
  },
  {
    name: 'Conservation within a protein (p53)',
    description:
      'p53 diffed against human — the central DNA-binding domain collapses to ' +
      'dots while the variable N/C-termini stay full of letters, showing where ' +
      'selection acts within one protein.',
    Component: P53,
    source: P53Src,
  },
  {
    name: 'One conserved domain (Hox homeodomain)',
    description:
      'Hox transcription factors are wildly divergent except for the ~60-residue ' +
      'homeodomain they all share — the InterProScan overlay marks the one ' +
      'block that stays conserved across the family.',
    Component: Hox,
    source: HoxSrc,
  },
  {
    name: 'Tree of life (EF-1α / EF-Tu)',
    description:
      'Elongation factor across all three domains of life (bacteria, archaea, ' +
      'eukaryotes) in one alignment — a universal protein used to probe the ' +
      'deepest splits in the tree of life.',
    Component: Ef1a,
    source: Ef1aSrc,
  },
  {
    name: 'Processing vs conservation (insulin)',
    description:
      'Preproinsulin across vertebrates diffed against human — the B and A ' +
      'chains of mature insulin stay conserved (dots) while the cleaved-out ' +
      'C-peptide drifts (letters).',
    Component: Insulin,
    source: InsulinSrc,
  },
  {
    name: 'Load from URL',
    description:
      'Fetch a remote Stockholm alignment plus an InterProScan domain GFF.',
    Component: LoadFromUrl,
    source: LoadFromUrlSrc,
  },
]
