import type { ComponentType } from 'react'

import ColorSchemes from './ColorSchemes'
import ColorSchemesSrc from './ColorSchemes.tsx?raw'
import Domains from './Domains'
import DomainsSrc from './Domains.tsx?raw'
import LargeTree from './LargeTree'
import LargeTreeSrc from './LargeTree.tsx?raw'
import LoadFromUrl from './LoadFromUrl'
import LoadFromUrlSrc from './LoadFromUrl.tsx?raw'
import ModelApi from './ModelApi'
import ModelApiSrc from './ModelApi.tsx?raw'
import NucleotideAlignment from './NucleotideAlignment'
import NucleotideAlignmentSrc from './NucleotideAlignment.tsx?raw'
import ProgrammaticControl from './ProgrammaticControl'
import ProgrammaticControlSrc from './ProgrammaticControl.tsx?raw'
import RealDomains from './RealDomains'
import RealDomainsSrc from './RealDomains.tsx?raw'
import TreeOptions from './TreeOptions'
import TreeOptionsSrc from './TreeOptions.tsx?raw'
import ZeroConfig from './ZeroConfig'
import ZeroConfigSrc from './ZeroConfig.tsx?raw'

export interface Example {
  name: string
  description: string
  Component: ComponentType
  source: string
}

export const examples: Example[] = [
  {
    name: 'Zero-config viewer',
    description:
      'The simplest usage: pass alignment + tree text as strings to MSAViewer.',
    Component: ZeroConfig,
    source: ZeroConfigSrc,
  },
  {
    name: 'Nucleotide alignment',
    description:
      'A DNA alignment with no tree, using a nucleotide color scheme.',
    Component: NucleotideAlignment,
    source: NucleotideAlignmentSrc,
  },
  {
    name: 'Color schemes',
    description:
      'Switch color schemes at runtime via model.setColorSchemeName.',
    Component: ColorSchemes,
    source: ColorSchemesSrc,
  },
  {
    name: 'Model API',
    description:
      'Create the model yourself with MSAModelF and render it with MSAView.',
    Component: ModelApi,
    source: ModelApiSrc,
  },
  {
    name: 'Programmatic control',
    description: 'Drive the viewer by calling model actions from buttons.',
    Component: ProgrammaticControl,
    source: ProgrammaticControlSrc,
  },
  {
    name: 'Tree options',
    description:
      'Toggle branch lengths, label alignment, node bubbles, and the tree panel.',
    Component: TreeOptions,
    source: TreeOptionsSrc,
  },
  {
    name: 'Protein domains',
    description:
      'Overlay InterProScan domain annotations from an inline GFF3 string.',
    Component: Domains,
    source: DomainsSrc,
  },
  {
    name: 'Real domains (Src-family kinases)',
    description:
      'A real Src-family kinase family (SRC, FYN, LCK, ...) with its tree and ' +
      'real InterProScan annotations — the signature SH3 + SH2 + kinase ' +
      'domains generated by react-msaview-cli interproscan.',
    Component: RealDomains,
    source: RealDomainsSrc,
  },
  {
    name: 'Large tree (Lysine riboswitch)',
    description:
      'A real ~60 sequence ncRNA family (Rfam Lysine riboswitch) with its ' +
      'full inferred tree — shows the canvas tiling holds up past toy data.',
    Component: LargeTree,
    source: LargeTreeSrc,
  },
  {
    name: 'Load from URL',
    description:
      'Fetch a remote Stockholm alignment plus an InterProScan domain GFF.',
    Component: LoadFromUrl,
    source: LoadFromUrlSrc,
  },
]
