import { MSAViewer } from 'react-msaview'

import { kinaseDomainsGFF, kinaseMSA, kinaseTree } from './exampleData'

// A real Src-family kinase (SFK) family — SRC, YES, FYN, FGR, HCK, LYN, LCK,
// BLK — with its tree and real InterProScan domain annotations generated by
// `react-msaview-cli interproscan`. Every member shares the signature
// SH3 + SH2 + tyrosine-kinase catalytic architecture, drawn as three labelled
// boxes per row over the alignment.
export default function RealDomains() {
  return (
    <MSAViewer
      msa={kinaseMSA}
      tree={kinaseTree}
      gff={kinaseDomainsGFF}
      colorScheme="clustalx_protein_dynamic"
      height={500}
    />
  )
}
