// @vitest-environment jsdom
//
// residueMappings.test.ts checks the lookups against fixtures written to make
// them pass. This checks them against the one real mapping in the repo --
// SIFTS' correspondence between the SRC_HUMAN row of the kinase alignment and
// chain A of 2SRC, generated by scripts/examples-gen/contacts.mjs -- loaded
// into the same model the app builds.
//
// It reaches into the examples package rather than living there: from there,
// `react-msaview` resolves through the package's node condition to dist/, so
// the test would exercise the last build rather than the source beside it.
// Tests are excluded from the lib's build config, so the reach never reaches
// the published package.
import { expect, test } from 'vitest'

import kinaseMSA from '../../examples/data/kinase.fa?raw'
import structure from '../../examples/src/examples/kinaseStructure.json'
import MSAModelF from './model.ts'

import type { ResidueMapping } from './types.ts'

const residueMappings = structure.residueMappings as ResidueMapping[]

function makeModel(mappings = residueMappings) {
  const model = MSAModelF().create({
    type: 'MsaView',
    msaFormat: 'fasta',
    data: { msa: kinaseMSA },
    residueMappings: mappings,
  })
  model.setWidth(1000)
  return model
}

test('the generated mapping fits the alignment it was generated from', () => {
  const model = makeModel()
  expect(model.residueMappingProblems).toEqual([])
  expect(model.usableResidueMappings).toHaveLength(1)
  expect(model.mappedStructures[0]).toEqual({
    row: 'SRC_HUMAN',
    structure: residueMappings[0]!.structure,
  })
})

test('the autoinhibitory phosphotyrosine maps to the residue it is', () => {
  const model = makeModel()
  // Tyr527 is the residue the SH2 domain binds to hold the kinase shut, and it
  // is what the contact arcs in this example converge on. SIFTS puts the row's
  // residue 86 at structure residue 2, so 527 lands at 443.
  const hit = model.structureResidue('SRC_HUMAN', 527)
  expect(hit).toEqual({
    structure: residueMappings[0]!.structure,
    position: 443,
    observed: true,
  })
  expect(model.rowResidue('2SRC', 443)).toEqual({
    rowName: 'SRC_HUMAN',
    seqPos: 527,
  })
})

test('residues the crystal did not resolve are mapped and not observed', () => {
  const model = makeModel()
  const [start] = residueMappings[0]!.unobserved![0]!
  const rowPos = model.rowResidue('2SRC', start)!.seqPos
  expect(model.structureResidue('SRC_HUMAN', rowPos)).toEqual({
    structure: residueMappings[0]!.structure,
    position: start,
    observed: false,
  })
})

test('the N-terminal region the structure does not cover is unmapped', () => {
  const model = makeModel()
  // the construct starts at residue 86; nothing before that has a structure,
  // and the answer is nothing rather than a plausible low-numbered residue
  expect(model.structureResidue('SRC_HUMAN', 85)).toBeUndefined()
  expect(model.structureResidue('SRC_HUMAN', 1)).toBeUndefined()
  expect(model.structureResidue('SRC_HUMAN', 86)?.position).toBe(2)
})

test('every other row of the family is unmapped, not assumed', () => {
  const model = makeModel()
  // the family aligns nine kinases and one of them has the structure. Chicken
  // Src is 92% identical to human and still gets nothing, which is the whole
  // argument for the layer: sequence similarity is not a correspondence.
  for (const row of ['SRC_CHICK', 'FYN_HUMAN', 'LCK_HUMAN']) {
    expect(model.structureResidue(row, 527)).toBeUndefined()
  }
})

test('the mapping is refused beside an alignment it was not made for', () => {
  const other = MSAModelF().create({
    type: 'MsaView',
    msaFormat: 'fasta',
    data: { msa: '>SRC_HUMAN\nMKAANSEQ\n>other\nMKAANSEQ' },
    residueMappings,
  })
  other.setWidth(1000)
  // same row name, 8 residues instead of 536: every lookup would still have
  // returned a residue, and every one of them would have been wrong
  expect(other.residueMappingProblems).toEqual([
    {
      row: 'SRC_HUMAN',
      structureId: '2SRC',
      scope: 'mapping',
      reason: 'computed against a 536-residue row; this one has 8',
    },
  ])
  expect(other.structureResidue('SRC_HUMAN', 5)).toBeUndefined()
})
