// @vitest-environment jsdom
//
// Checks the lookups against the SIFTS mapping between the kinase alignment's
// SRC_HUMAN row and chain A of 2SRC, generated by
// scripts/examples-gen/contacts.mjs.
//
// The test lives here because inside the examples package `react-msaview`
// resolves to dist/. The lib build excludes tests, so the import stays out of
// the published package.
import { expect, test } from 'vitest'

import kinaseMSA from '../../examples/data/kinase.aln?raw'
import structure from '../../examples/src/examples/kinaseStructure.json'
import MSAModelF from './model.ts'

import type { ResidueMapping } from './types.ts'

const residueMappings = structure.residueMappings as ResidueMapping[]

function makeModel(mappings = residueMappings) {
  const model = MSAModelF().create({
    type: 'MsaView',
    msaFormat: 'fasta',
    data: { msa: kinaseMSA },
    residueMappings: mappings,
  })
  model.setWidth(1000)
  return model
}

test('the generated mapping fits the alignment it was generated from', () => {
  const model = makeModel()
  expect(model.residueMappingProblems).toEqual([])
  expect(model.usableResidueMappings).toHaveLength(1)
  expect(model.mappedStructures[0]).toEqual({
    row: 'SRC_HUMAN',
    structure: residueMappings[0]!.structure,
  })
})

test('the autoinhibitory phosphotyrosine maps to the residue it is', () => {
  const model = makeModel()
  // the SH2 domain binds Tyr527 to hold the kinase shut. SIFTS puts the row's
  // residue 86 at structure residue 2, so 527 lands at 443.
  const hit = model.structureResidue('SRC_HUMAN', 527)
  expect(hit).toEqual({
    structure: residueMappings[0]!.structure,
    position: 443,
    observed: true,
  })
  expect(model.rowResidue('2SRC', 443)).toEqual({
    rowName: 'SRC_HUMAN',
    seqPos: 527,
  })
})

test('residues the crystal did not resolve are mapped and not observed', () => {
  const model = makeModel()
  const [start] = residueMappings[0]!.unobserved![0]!
  const rowPos = model.rowResidue('2SRC', start)!.seqPos
  expect(model.structureResidue('SRC_HUMAN', rowPos)).toEqual({
    structure: residueMappings[0]!.structure,
    position: start,
    observed: false,
  })
})

test('the N-terminal region the structure does not cover is unmapped', () => {
  const model = makeModel()
  // the construct starts at residue 86
  expect(model.structureResidue('SRC_HUMAN', 85)).toBeUndefined()
  expect(model.structureResidue('SRC_HUMAN', 1)).toBeUndefined()
  expect(model.structureResidue('SRC_HUMAN', 86)?.position).toBe(2)
})

test('every other row of the family is unmapped, not assumed', () => {
  const model = makeModel()
  // chicken Src is 92% identical to human and has no mapping
  for (const row of ['SRC_CHICK', 'FYN_HUMAN', 'LCK_HUMAN']) {
    expect(model.structureResidue(row, 527)).toBeUndefined()
  }
})

test('the mapping is refused beside an alignment it was not made for', () => {
  const other = MSAModelF().create({
    type: 'MsaView',
    msaFormat: 'fasta',
    data: { msa: '>SRC_HUMAN\nMKAANSEQ\n>other\nMKAANSEQ' },
    residueMappings,
  })
  other.setWidth(1000)
  // same row name, 8 residues instead of 536
  expect(other.residueMappingProblems).toEqual([
    {
      row: 'SRC_HUMAN',
      structureId: '2SRC',
      scope: 'mapping',
      reason: 'computed against a 536-residue row; this one has 8',
    },
  ])
  expect(other.structureResidue('SRC_HUMAN', 5)).toBeUndefined()
})
