/**
 * Rewrite the markdown reference-link block at the bottom of docs/user_guide.md
 * so each figure links to the live demo app loaded into that exact state via the
 * `?data=` URL-param API. The screenshot specs are the single source of truth,
 * so the live links stay in lockstep with the figures.
 *
 * Only emits definitions for the `[live-*]` refs the guide uses (the
 * specs are a superset, and some feed other docs), so growing specs.mjs never
 * bloats the guide with unused links. Errors if the guide references a figure
 * with no matching spec.
 *
 *   node scripts/screenshots/genGuideLinks.mjs            rewrites the file
 *   node scripts/screenshots/genGuideLinks.mjs --check    fails if it is stale
 *
 * `--check` (CI runs it as `pnpm check:guide-links`) exists because the drift is
 * invisible: editing a spec changes the figure on the next capture but leaves
 * the guide's link pointing at the state the figure used to show, so a reader
 * clicks a screenshot and lands somewhere that does not match it. `pfam-scale`
 * sat that way through three parameter changes.
 *
 * The comparison ignores line wrapping, since oxfmt wraps a definition past 80
 * columns and this script writes each on one line. Run the generator and then
 * `pnpm format`; that round trip is a no-op on an up-to-date guide.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { specs } from './specs.mjs'

const DEMO = 'https://gmod.org/JBrowseMSA/demo/'
const MARKER = '<!-- live-demo links (generated by genGuideLinks.mjs) -->'

const guidePath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../docs/user_guide.md',
)
const guide = fs.readFileSync(guidePath, 'utf8')

const urlByName = new Map(specs.map(s => [s.name, `${DEMO}${s.url ?? ''}`]))
const used = [...guide.matchAll(/\]\[live-([a-z-]+)\]/g)].map(m => m[1])
const unique = [...new Set(used)]

const missing = unique.filter(n => !urlByName.has(n))
if (missing.length) {
  throw new Error(
    `guide references figures with no spec: ${missing.join(', ')}`,
  )
}
// A compose spec has no url of its own (it stacks other specs' captures), so a
// live link for one would resolve to the bare demo app instead of the
// state the figure shows. Embed those figures without a [live-*] ref.
// (url: '' is a real state, the import form on the demo app's landing page,
// so this tests for the absent url of a compose spec, not a falsy one)
const composed = unique.filter(
  n => specs.find(s => s.name === n)?.url === undefined,
)
if (composed.length) {
  throw new Error(
    `guide references composed figures, which have no live state to link to: ${composed.join(', ')}`,
  )
}

const block = [
  MARKER,
  ...unique.map(name => `[live-${name}]: ${urlByName.get(name)}`),
].join('\n')

// replace an existing generated block (from MARKER to EOF), or append one
const body = guide.includes(MARKER)
  ? guide.slice(0, guide.indexOf(MARKER))
  : `${guide.replace(/\s*$/, '')}\n\n`

// each [live-*]: url pair, with the wrapping oxfmt may have applied collapsed
// away, so --check compares link targets rather than line breaks
const pairs = text =>
  Object.fromEntries(
    [
      ...text.replaceAll(/\n\s+/g, ' ').matchAll(/\[(live-[\w-]+)\]:\s*(\S+)/g),
    ].map(m => [m[1], m[2]]),
  )

if (process.argv.includes('--check')) {
  const want = pairs(block)
  const have = pairs(guide.slice(guide.indexOf(MARKER)))
  const stale = [...new Set([...Object.keys(want), ...Object.keys(have)])]
    .filter(name => want[name] !== have[name])
    .map(
      name =>
        `  [${name}] ${have[name] ? 'points at a stale state' : 'is missing'}`,
    )
  if (stale.length > 0) {
    console.error(
      `docs/user_guide.md live links are out of date with the screenshot specs:\n${stale.join('\n')}\n\n` +
        'Run: node scripts/screenshots/genGuideLinks.mjs && pnpm format',
    )
    process.exit(1)
  }
  console.log(`${Object.keys(want).length} live-demo links match their specs`)
} else {
  fs.writeFileSync(guidePath, `${body}${block}\n`)
  console.log(`wrote ${unique.length} live-demo links to docs/user_guide.md`)
}
