/**
 * Rewrite the markdown reference-link block at the bottom of each doc in DOCS so
 * every figure links to the live demo app loaded into that exact state via the
 * `#data=` URL API. The screenshot specs are the single source of truth,
 * so the live links stay in lockstep with the figures.
 *
 * A doc gets definitions only for the `[live-*]` refs it uses (the specs are a
 * superset, and each doc uses a few of them), so growing specs.mjs never bloats
 * a page with unused links. Errors if a doc references a figure with no
 * matching spec.
 *
 *   node scripts/screenshots/genGuideLinks.mjs            rewrites the files
 *   node scripts/screenshots/genGuideLinks.mjs --check    fails if one is stale
 *
 * `--check` (CI runs it as `pnpm check:guide-links`) exists because the drift is
 * invisible: editing a spec changes the figure on the next capture but leaves
 * the doc's link pointing at the state the figure used to show, so a reader
 * clicks a screenshot and lands somewhere that does not match it. `pfam-scale`
 * sat that way through three parameter changes.
 *
 * The comparison ignores line wrapping, since oxfmt wraps a definition past 80
 * columns and this script writes each on one line. Run the generator and then
 * `pnpm format`; that round trip is a no-op on an up-to-date doc.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { linkSpecs } from './layers-specs.mjs'
import { specs as figureSpecs } from './specs.mjs'

const DEMO = 'https://gmod.org/JBrowseMSA/demo/'
const MARKER = '<!-- live-demo links (generated by genGuideLinks.mjs) -->'
const DOCS = ['docs/user_guide.md', 'docs/layers.md']

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../..',
)
const specs = [...figureSpecs, ...linkSpecs]
const urlByName = new Map(specs.map(s => [s.name, `${DEMO}${s.url ?? ''}`]))

// each [live-*]: url pair, with the wrapping oxfmt may have applied collapsed
// away, so --check compares link targets rather than line breaks
const pairs = text =>
  Object.fromEntries(
    [
      ...text.replaceAll(/\n\s+/g, ' ').matchAll(/\[(live-[\w-]+)\]:\s*(\S+)/g),
    ].map(m => [m[1], m[2]]),
  )

function blockFor(doc, text) {
  const unique = [
    ...new Set([...text.matchAll(/\]\[live-([\w-]+)\]/g)].map(m => m[1])),
  ]

  const missing = unique.filter(n => !urlByName.has(n))
  if (missing.length) {
    throw new Error(
      `${doc} references figures with no spec: ${missing.join(', ')}`,
    )
  }
  // A compose spec has no url of its own (it stacks other specs' captures), so
  // a live link for one would resolve to the bare demo app instead of the state
  // the figure shows. Embed those figures without a [live-*] ref.
  // (url: '' is a real state, the import form on the demo app's landing page,
  // so this tests for the absent url of a compose spec, not a falsy one)
  const composed = unique.filter(
    n => specs.find(s => s.name === n)?.url === undefined,
  )
  if (composed.length) {
    throw new Error(
      `${doc} references composed figures, which have no live state to link to: ${composed.join(', ')}`,
    )
  }

  return [
    MARKER,
    ...unique.map(name => `[live-${name}]: ${urlByName.get(name)}`),
  ].join('\n')
}

const check = process.argv.includes('--check')
const stale = []
let written = 0

for (const doc of DOCS) {
  const file = path.join(repoRoot, doc)
  const text = fs.readFileSync(file, 'utf8')
  const block = blockFor(doc, text)

  if (check) {
    const want = pairs(block)
    const have = pairs(
      text.includes(MARKER) ? text.slice(text.indexOf(MARKER)) : '',
    )
    for (const name of new Set([...Object.keys(want), ...Object.keys(have)])) {
      if (want[name] !== have[name]) {
        stale.push(
          `  ${doc} [${name}] ${have[name] ? 'points at a stale state' : 'is missing'}`,
        )
      }
    }
    written += Object.keys(want).length
    continue
  }

  // replace an existing generated block (from MARKER to EOF), or append one
  const body = text.includes(MARKER)
    ? text.slice(0, text.indexOf(MARKER))
    : `${text.replace(/\s*$/, '')}\n\n`
  fs.writeFileSync(file, `${body}${block}\n`)
  written += Object.keys(pairs(block)).length
}

if (check) {
  if (stale.length > 0) {
    console.error(
      `live links are out of date with the screenshot specs:\n${stale.join('\n')}\n\n` +
        'Run: node scripts/screenshots/genGuideLinks.mjs && pnpm format',
    )
    process.exit(1)
  }
  console.log(`${written} live-demo links match their specs`)
} else {
  console.log(`wrote ${written} live-demo links to ${DOCS.join(', ')}`)
}
