/**
 * Rewrite the markdown reference-link block at the bottom of docs/user_guide.md
 * so each figure links to the live demo app loaded into that exact state via the
 * `?data=` URL-param API. The screenshot specs are the single source of truth,
 * so the live links stay in lockstep with the figures.
 *
 * Only emits definitions for the `[live-*]` refs the guide actually uses (the
 * specs are a superset — some feed other docs), so growing specs.mjs never
 * bloats the guide with unused links. Errors if the guide references a figure
 * with no matching spec.
 *
 * Run with:  node scripts/screenshots/genGuideLinks.mjs   (rewrites the file)
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { specs } from './specs.mjs'

const DEMO = 'https://gmod.org/JBrowseMSA/demo/'
const MARKER = '<!-- live-demo links (generated by genGuideLinks.mjs) -->'

const guidePath = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../docs/user_guide.md',
)
const guide = fs.readFileSync(guidePath, 'utf8')

const urlByName = new Map(specs.map(s => [s.name, `${DEMO}${s.url ?? ''}`]))
const used = [...guide.matchAll(/\]\[live-([a-z-]+)\]/g)].map(m => m[1])
const unique = [...new Set(used)]

const missing = unique.filter(n => !urlByName.has(n))
if (missing.length) {
  throw new Error(
    `guide references figures with no spec: ${missing.join(', ')}`,
  )
}

const block = [
  MARKER,
  ...unique.map(name => `[live-${name}]: ${urlByName.get(name)}`),
].join('\n')

// replace an existing generated block (from MARKER to EOF), or append one
const body = guide.includes(MARKER)
  ? guide.slice(0, guide.indexOf(MARKER))
  : `${guide.replace(/\s*$/, '')}\n\n`
fs.writeFileSync(guidePath, `${body}${block}\n`)
console.log(`wrote ${unique.length} live-demo links to docs/user_guide.md`)
